version: "2"
services:
  selenium-hub:
    image: softcrylicqa/selenium-hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: softcrylicqa/headless-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
